version: '3'
services:
  vending_machine_service:
    image: vending_machine_service:1.0
    build: .
    ports:
      - 5000:5000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db_container:3306/vending_machine?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SERVER_PORT: 5000

  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vending_machine
    ports:
      - 3307:3306
    volumes:
      - vending_machine_mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8089:8080

volumes:
  vending_machine_mysql_db_data_container: